package org.freakz.hokan_ng_springboot.bot.common.events;

/**
 * Created by Petri Airio (petri.j.airio@gmail.com) on 26.4.2015.
 * -
 */
public enum ServiceRequestType {

    ALKO_SEARCH_REQUEST("ALKO_SEARCH_RESPONSE"),
    CATCH_URLS_REQUEST("NO_RESPONSE"),
    CHARSET_REQUEST("CHARSET_REQUEST"),
    CHANNEL_TOPIC_GET_REQUEST("CHANNEL_TOPIC_GET_REQUEST"),
    CHANNEL_TOPIC_SET_REQUEST("CHANNEL_TOPIC_SET_REQUEST"),
    CURRENCY_CONVERT_REQUEST("CURRENCY_CONVERT_RESPONSE"),
    CURRENCY_LIST_REQUEST("CURRENCY_LIST_RESPONSE"),
    FIND_CITY_REQUEST("FIND_CITY_RESPONSE"),
    FORECA_WEATHER_HOURLY_REQUEST("FORECA_WEATHER_HOURLY_RESPONSE"),
    HORO_REQUEST("HORO_DATA_RESPONSE"),
    KORONA_REQUEST("KORONA_RESPONSE"),
    KORONA_NOTIFY_REQUEST("KORONA_NOTIFY_RESPONSE"),
    LUNCH_REQUEST("LUNCH_RESPONSE"),
    LUNCH_PLACES_REQUEST("LUNCH_PLACES_RESPONSE"),
    ILMATIETEENLAITOS_HOURLY_REQUEST("ILMATIETEENLAITOS_HOURLY_RESPONSE"),
    IMDB_DETAILED_INFO_REQUEST("IMDB_DETAILED_INFO_DATA_RESPONSE"),
    IMDB_TITLE_REQUEST("IMDB_TITLE_DATA_RESPONSE"),
    IRC_CHANNEL_LOG_REQUEST("NO_RESPONSE"),
    MATKA_REQUEST("MATKA_DATA_RESPONSE"),
    METAR_REQUEST("METAR_DATA_RESPONSE"),
    NIMIPAIVA_DAY_REQUEST("NIMIPAIVA_DAY_RESPONSE"),
    NIMIPAIVA_NAME_REQUEST("NIMIPAIVA_NAME_RESPONSE"),
    SCRIPT_SERVICE_REQUEST("SCRIPT_SERVICE_RESPONSE"),
    SMS_CREDIT_SERVICE_REQUEST("SMS_CREDIT_RESPONSE"),
    SMS_SEND_SERVICE_REQUEST("SMS_SEND_RESPONSE"),
    SUNRISE_SERVICE_REQUEST("SUNRISE_SERVICE_RESPONSE"),
    TOP_COUNT_REQUEST("NO_RESPONSE"),
    TRANSLATE_REQUEST("TRANSLATE_RESPONSE"),
    UPDATERS_LIST_REQUEST("UPDATER_LIST_RESPONSE"),
    UPDATERS_START_REQUEST("UPDATER_START_RESPONSE"),
    WEATHER_REQUEST("WEATHER_DATA_RESPONSE"),
    WHOLE_LINE_TRIGGER("NO_RESPONSE");

    final private String responseDataKey;

    ServiceRequestType(String responseDataKey) {
        this.responseDataKey = responseDataKey;
    }

    public String getResponseDataKey() {
        return responseDataKey;
    }

}
